[package]
name = "code-executor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sandkasten-client = "0.2.2"
tokio = { version = "1.40.0", features = ["full"] }
rocket = "0.5.1"
